export type Currency = {
  code: string;
  name: string;
  flag: string;
  country: string;
  symbol: string;
};

export const currencies: Currency[] = [
  { code: "AED", name: "UAE Dirham", flag: "🇦🇪", country: "United Arab Emirates", symbol: "د.إ" },
  { code: "AFN", name: "Afghan Afghani", flag: "🇦🇫", country: "Afghanistan", symbol: "؋" },
  { code: "ALL", name: "Albanian Lek", flag: "🇦🇱", country: "Albania", symbol: "L" },
  { code: "AMD", name: "Armenian Dram", flag: "🇦🇲", country: "Armenia", symbol: "֏" },
  {
    code: "ANG",
    name: "Netherlands Antillean Guilder",
    flag: "🇨🇼",
    country: "Curaçao",
    symbol: "ƒ",
  },
  { code: "AOA", name: "Angolan Kwanza", flag: "🇦🇴", country: "Angola", symbol: "Kz" },
  { code: "ARS", name: "Argentine Peso", flag: "🇦🇷", country: "Argentina", symbol: "$" },
  { code: "AUD", name: "Australian Dollar", flag: "🇦🇺", country: "Australia", symbol: "A$" },
  { code: "AWG", name: "Aruban Florin", flag: "🇦🇼", country: "Aruba", symbol: "ƒ" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "🇦🇿", country: "Azerbaijan", symbol: "₼" },
  {
    code: "BAM",
    name: "Bosnia-Herzegovina Mark",
    flag: "🇧🇦",
    country: "Bosnia and Herzegovina",
    symbol: "KM",
  },
  { code: "BBD", name: "Barbadian Dollar", flag: "🇧🇧", country: "Barbados", symbol: "Bds$" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "🇧🇩", country: "Bangladesh", symbol: "৳" },
  { code: "BGN", name: "Bulgarian Lev", flag: "🇧🇬", country: "Bulgaria", symbol: "лв" },
  { code: "BHD", name: "Bahraini Dinar", flag: "🇧🇭", country: "Bahrain", symbol: "BD" },
  { code: "BIF", name: "Burundian Franc", flag: "🇧🇮", country: "Burundi", symbol: "FBu" },
  { code: "BMD", name: "Bermudian Dollar", flag: "🇧🇲", country: "Bermuda", symbol: "$" },
  { code: "BND", name: "Brunei Dollar", flag: "🇧🇳", country: "Brunei", symbol: "B$" },
  { code: "BOB", name: "Bolivian Boliviano", flag: "🇧🇴", country: "Bolivia", symbol: "Bs" },
  { code: "BRL", name: "Brazilian Real", flag: "🇧🇷", country: "Brazil", symbol: "R$" },
  { code: "BSD", name: "Bahamian Dollar", flag: "🇧🇸", country: "Bahamas", symbol: "B$" },
  { code: "BTN", name: "Bhutanese Ngultrum", flag: "🇧🇹", country: "Bhutan", symbol: "Nu" },
  { code: "BWP", name: "Botswanan Pula", flag: "🇧🇼", country: "Botswana", symbol: "P" },
  { code: "BYN", name: "Belarusian Ruble", flag: "🇧🇾", country: "Belarus", symbol: "Br" },
  { code: "BZD", name: "Belize Dollar", flag: "🇧🇿", country: "Belize", symbol: "BZ$" },
  { code: "CAD", name: "Canadian Dollar", flag: "🇨🇦", country: "Canada", symbol: "C$" },
  { code: "CDF", name: "Congolese Franc", flag: "🇨🇩", country: "DR Congo", symbol: "FC" },
  { code: "CHF", name: "Swiss Franc", flag: "🇨🇭", country: "Switzerland", symbol: "Fr" },
  { code: "CLP", name: "Chilean Peso", flag: "🇨🇱", country: "Chile", symbol: "$" },
  { code: "CNY", name: "Chinese Yuan", flag: "🇨🇳", country: "China", symbol: "¥" },
  { code: "COP", name: "Colombian Peso", flag: "🇨🇴", country: "Colombia", symbol: "$" },
  { code: "CRC", name: "Costa Rican Colón", flag: "🇨🇷", country: "Costa Rica", symbol: "₡" },
  { code: "CUP", name: "Cuban Peso", flag: "🇨🇺", country: "Cuba", symbol: "$" },
  { code: "CVE", name: "Cape Verdean Escudo", flag: "🇨🇻", country: "Cape Verde", symbol: "Esc" },
  { code: "CZK", name: "Czech Koruna", flag: "🇨🇿", country: "Czech Republic", symbol: "Kč" },
  { code: "DJF", name: "Djiboutian Franc", flag: "🇩🇯", country: "Djibouti", symbol: "Fdj" },
  { code: "DKK", name: "Danish Krone", flag: "🇩🇰", country: "Denmark", symbol: "kr" },
  { code: "DOP", name: "Dominican Peso", flag: "🇩🇴", country: "Dominican Republic", symbol: "RD$" },
  { code: "DZD", name: "Algerian Dinar", flag: "🇩🇿", country: "Algeria", symbol: "د.ج" },
  { code: "EGP", name: "Egyptian Pound", flag: "🇪🇬", country: "Egypt", symbol: "E£" },
  { code: "ERN", name: "Eritrean Nakfa", flag: "🇪🇷", country: "Eritrea", symbol: "Nfk" },
  { code: "ETB", name: "Ethiopian Birr", flag: "🇪🇹", country: "Ethiopia", symbol: "Br" },
  { code: "EUR", name: "Euro", flag: "🇪🇺", country: "Eurozone", symbol: "€" },
  { code: "FJD", name: "Fijian Dollar", flag: "🇫🇯", country: "Fiji", symbol: "FJ$" },
  {
    code: "FKP",
    name: "Falkland Islands Pound",
    flag: "🇫🇰",
    country: "Falkland Islands",
    symbol: "£",
  },
  { code: "GBP", name: "British Pound", flag: "🇬🇧", country: "United Kingdom", symbol: "£" },
  { code: "GEL", name: "Georgian Lari", flag: "🇬🇪", country: "Georgia", symbol: "₾" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "🇬🇭", country: "Ghana", symbol: "GH₵" },
  { code: "GIP", name: "Gibraltar Pound", flag: "🇬🇮", country: "Gibraltar", symbol: "£" },
  { code: "GMD", name: "Gambian Dalasi", flag: "🇬🇲", country: "Gambia", symbol: "D" },
  { code: "GNF", name: "Guinean Franc", flag: "🇬🇳", country: "Guinea", symbol: "FG" },
  { code: "GTQ", name: "Guatemalan Quetzal", flag: "🇬🇹", country: "Guatemala", symbol: "Q" },
  { code: "GYD", name: "Guyanese Dollar", flag: "🇬🇾", country: "Guyana", symbol: "G$" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "🇭🇰", country: "Hong Kong", symbol: "HK$" },
  { code: "HNL", name: "Honduran Lempira", flag: "🇭🇳", country: "Honduras", symbol: "L" },
  { code: "HRK", name: "Croatian Kuna", flag: "🇭🇷", country: "Croatia", symbol: "kn" },
  { code: "HTG", name: "Haitian Gourde", flag: "🇭🇹", country: "Haiti", symbol: "G" },
  { code: "HUF", name: "Hungarian Forint", flag: "🇭🇺", country: "Hungary", symbol: "Ft" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "🇮🇩", country: "Indonesia", symbol: "Rp" },
  { code: "ILS", name: "Israeli Shekel", flag: "🇮🇱", country: "Israel", symbol: "₪" },
  { code: "INR", name: "Indian Rupee", flag: "🇮🇳", country: "India", symbol: "₹" },
  { code: "IQD", name: "Iraqi Dinar", flag: "🇮🇶", country: "Iraq", symbol: "ع.د" },
  { code: "IRR", name: "Iranian Rial", flag: "🇮🇷", country: "Iran", symbol: "﷼" },
  { code: "ISK", name: "Icelandic Krona", flag: "🇮🇸", country: "Iceland", symbol: "kr" },
  { code: "JMD", name: "Jamaican Dollar", flag: "🇯🇲", country: "Jamaica", symbol: "J$" },
  { code: "JOD", name: "Jordanian Dinar", flag: "🇯🇴", country: "Jordan", symbol: "JD" },
  { code: "JPY", name: "Japanese Yen", flag: "🇯🇵", country: "Japan", symbol: "¥" },
  { code: "KES", name: "Kenyan Shilling", flag: "🇰🇪", country: "Kenya", symbol: "KSh" },
  { code: "KGS", name: "Kyrgystani Som", flag: "🇰🇬", country: "Kyrgyzstan", symbol: "сом" },
  { code: "KHR", name: "Cambodian Riel", flag: "🇰🇭", country: "Cambodia", symbol: "៛" },
  { code: "KMF", name: "Comorian Franc", flag: "🇰🇲", country: "Comoros", symbol: "CF" },
  { code: "KRW", name: "South Korean Won", flag: "🇰🇷", country: "South Korea", symbol: "₩" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "🇰🇼", country: "Kuwait", symbol: "KD" },
  {
    code: "KYD",
    name: "Cayman Islands Dollar",
    flag: "🇰🇾",
    country: "Cayman Islands",
    symbol: "CI$",
  },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "🇰🇿", country: "Kazakhstan", symbol: "₸" },
  { code: "LAK", name: "Lao Kip", flag: "🇱🇦", country: "Laos", symbol: "₭" },
  { code: "LBP", name: "Lebanese Pound", flag: "🇱🇧", country: "Lebanon", symbol: "L£" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "🇱🇰", country: "Sri Lanka", symbol: "Rs" },
  { code: "LRD", name: "Liberian Dollar", flag: "🇱🇷", country: "Liberia", symbol: "L$" },
  { code: "LSL", name: "Lesotho Loti", flag: "🇱🇸", country: "Lesotho", symbol: "L" },
  { code: "LYD", name: "Libyan Dinar", flag: "🇱🇾", country: "Libya", symbol: "LD" },
  { code: "MAD", name: "Moroccan Dirham", flag: "🇲🇦", country: "Morocco", symbol: "MAD" },
  { code: "MDL", name: "Moldovan Leu", flag: "🇲🇩", country: "Moldova", symbol: "L" },
  { code: "MGA", name: "Malagasy Ariary", flag: "🇲🇬", country: "Madagascar", symbol: "Ar" },
  { code: "MKD", name: "Macedonian Denar", flag: "🇲🇰", country: "North Macedonia", symbol: "ден" },
  { code: "MMK", name: "Myanmar Kyat", flag: "🇲🇲", country: "Myanmar", symbol: "K" },
  { code: "MNT", name: "Mongolian Tugrik", flag: "🇲🇳", country: "Mongolia", symbol: "₮" },
  { code: "MOP", name: "Macanese Pataca", flag: "🇲🇴", country: "Macau", symbol: "MOP$" },
  { code: "MRU", name: "Mauritanian Ouguiya", flag: "🇲🇷", country: "Mauritania", symbol: "UM" },
  { code: "MUR", name: "Mauritian Rupee", flag: "🇲🇺", country: "Mauritius", symbol: "Rs" },
  { code: "MVR", name: "Maldivian Rufiyaa", flag: "🇲🇻", country: "Maldives", symbol: "Rf" },
  { code: "MWK", name: "Malawian Kwacha", flag: "🇲🇼", country: "Malawi", symbol: "MK" },
  { code: "MXN", name: "Mexican Peso", flag: "🇲🇽", country: "Mexico", symbol: "$" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "🇲🇾", country: "Malaysia", symbol: "RM" },
  { code: "MZN", name: "Mozambican Metical", flag: "🇲🇿", country: "Mozambique", symbol: "MT" },
  { code: "NAD", name: "Namibian Dollar", flag: "🇳🇦", country: "Namibia", symbol: "N$" },
  { code: "NGN", name: "Nigerian Naira", flag: "🇳🇬", country: "Nigeria", symbol: "₦" },
  { code: "NIO", name: "Nicaraguan Córdoba", flag: "🇳🇮", country: "Nicaragua", symbol: "C$" },
  { code: "NOK", name: "Norwegian Krone", flag: "🇳🇴", country: "Norway", symbol: "kr" },
  { code: "NPR", name: "Nepalese Rupee", flag: "🇳🇵", country: "Nepal", symbol: "Rs" },
  { code: "NZD", name: "New Zealand Dollar", flag: "🇳🇿", country: "New Zealand", symbol: "NZ$" },
  { code: "OMR", name: "Omani Rial", flag: "🇴🇲", country: "Oman", symbol: "OMR" },
  { code: "PAB", name: "Panamanian Balboa", flag: "🇵🇦", country: "Panama", symbol: "B/" },
  { code: "PEN", name: "Peruvian Sol", flag: "🇵🇪", country: "Peru", symbol: "S/" },
  {
    code: "PGK",
    name: "Papua New Guinean Kina",
    flag: "🇵🇬",
    country: "Papua New Guinea",
    symbol: "K",
  },
  { code: "PHP", name: "Philippine Peso", flag: "🇵🇭", country: "Philippines", symbol: "₱" },
  { code: "PKR", name: "Pakistani Rupee", flag: "🇵🇰", country: "Pakistan", symbol: "₨" },
  { code: "PLN", name: "Polish Zloty", flag: "🇵🇱", country: "Poland", symbol: "zł" },
  { code: "PYG", name: "Paraguayan Guarani", flag: "🇵🇾", country: "Paraguay", symbol: "₲" },
  { code: "QAR", name: "Qatari Riyal", flag: "🇶🇦", country: "Qatar", symbol: "QR" },
  { code: "RON", name: "Romanian Leu", flag: "🇷🇴", country: "Romania", symbol: "lei" },
  { code: "RSD", name: "Serbian Dinar", flag: "🇷🇸", country: "Serbia", symbol: "din" },
  { code: "RUB", name: "Russian Ruble", flag: "🇷🇺", country: "Russia", symbol: "₽" },
  { code: "RWF", name: "Rwandan Franc", flag: "🇷🇼", country: "Rwanda", symbol: "RF" },
  { code: "SAR", name: "Saudi Riyal", flag: "🇸🇦", country: "Saudi Arabia", symbol: "SR" },
  {
    code: "SBD",
    name: "Solomon Islands Dollar",
    flag: "🇸🇧",
    country: "Solomon Islands",
    symbol: "SI$",
  },
  { code: "SCR", name: "Seychellois Rupee", flag: "🇸🇨", country: "Seychelles", symbol: "Rs" },
  { code: "SDG", name: "Sudanese Pound", flag: "🇸🇩", country: "Sudan", symbol: "£" },
  { code: "SEK", name: "Swedish Krona", flag: "🇸🇪", country: "Sweden", symbol: "kr" },
  { code: "SGD", name: "Singapore Dollar", flag: "🇸🇬", country: "Singapore", symbol: "S$" },
  { code: "SHP", name: "Saint Helena Pound", flag: "🇸🇭", country: "Saint Helena", symbol: "£" },
  { code: "SLE", name: "Sierra Leonean Leone", flag: "🇸🇱", country: "Sierra Leone", symbol: "Le" },
  { code: "SOS", name: "Somali Shilling", flag: "🇸🇴", country: "Somalia", symbol: "Sh" },
  { code: "SRD", name: "Surinamese Dollar", flag: "🇸🇷", country: "Suriname", symbol: "Sr$" },
  { code: "SSP", name: "South Sudanese Pound", flag: "🇸🇸", country: "South Sudan", symbol: "£" },
  {
    code: "STN",
    name: "São Tomé and Príncipe Dobra",
    flag: "🇸🇹",
    country: "São Tomé and Príncipe",
    symbol: "Db",
  },
  { code: "SYP", name: "Syrian Pound", flag: "🇸🇾", country: "Syria", symbol: "£S" },
  { code: "SZL", name: "Eswatini Lilangeni", flag: "🇸🇿", country: "Eswatini", symbol: "E" },
  { code: "THB", name: "Thai Baht", flag: "🇹🇭", country: "Thailand", symbol: "฿" },
  { code: "TJS", name: "Tajikistani Somoni", flag: "🇹🇯", country: "Tajikistan", symbol: "SM" },
  { code: "TMT", name: "Turkmenistani Manat", flag: "🇹🇲", country: "Turkmenistan", symbol: "T" },
  { code: "TND", name: "Tunisian Dinar", flag: "🇹🇳", country: "Tunisia", symbol: "DT" },
  { code: "TOP", name: "Tongan Paʻanga", flag: "🇹🇴", country: "Tonga", symbol: "T$" },
  { code: "TRY", name: "Turkish Lira", flag: "🇹🇷", country: "Turkey", symbol: "₺" },
  {
    code: "TTD",
    name: "Trinidad & Tobago Dollar",
    flag: "🇹🇹",
    country: "Trinidad and Tobago",
    symbol: "TT$",
  },
  { code: "TWD", name: "Taiwan Dollar", flag: "🇹🇼", country: "Taiwan", symbol: "NT$" },
  { code: "TZS", name: "Tanzanian Shilling", flag: "🇹🇿", country: "Tanzania", symbol: "TSh" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "🇺🇦", country: "Ukraine", symbol: "₴" },
  { code: "UGX", name: "Ugandan Shilling", flag: "🇺🇬", country: "Uganda", symbol: "USh" },
  { code: "USD", name: "US Dollar", flag: "🇺🇸", country: "United States", symbol: "$" },
  { code: "UYU", name: "Uruguayan Peso", flag: "🇺🇾", country: "Uruguay", symbol: "$U" },
  { code: "UZS", name: "Uzbekistani Som", flag: "🇺🇿", country: "Uzbekistan", symbol: "сўм" },
  { code: "VES", name: "Venezuelan Bolívar", flag: "🇻🇪", country: "Venezuela", symbol: "Bs" },
  { code: "VND", name: "Vietnamese Dong", flag: "🇻🇳", country: "Vietnam", symbol: "₫" },
  { code: "VUV", name: "Vanuatu Vatu", flag: "🇻🇺", country: "Vanuatu", symbol: "VT" },
  { code: "WST", name: "Samoan Tala", flag: "🇼🇸", country: "Samoa", symbol: "WS$" },
  { code: "YER", name: "Yemeni Rial", flag: "🇾🇪", country: "Yemen", symbol: "﷼" },
  { code: "ZAR", name: "South African Rand", flag: "🇿🇦", country: "South Africa", symbol: "R" },
  { code: "ZMW", name: "Zambian Kwacha", flag: "🇿🇲", country: "Zambia", symbol: "ZK" },
];

export const CURRENCIES = currencies.map((c) => c.code);

const currencyMap = new Map(currencies.map((c) => [c.code, c]));

export function getCurrency(code: string): Currency | undefined {
  return currencyMap.get(code);
}
